### ISSUE TITLE
Bugs in `hvp` 

### ISSUE THREAD

**Issue by KeAWang** [g-benton/hessian-eff-dim#1]
There are currently two bugs in the `hvp` function here:
https://github.com/g-benton/hessian-eff-dim/blob/09b1f9ddaedf3dd5df2328117e3c7c0f02e23d68/hess/utils.py#L151

First is that `rhs` should be transposed since `unflatten_like` expects `* x number of parameters`.

Second is that the call to `eval_hess_vec_prod` is missing `params`. 

As such, `get_hessian_eigs` doesn't run right now

**Comment by wjmaddox** [comment]
Thanks!

Resolved by 12886d6
