### ISSUE TITLE
ModuleNotFoundError: No module named 'swag.utils'

### ISSUE THREAD

**Issue by dptam** [g-benton/hessian-eff-dim#2]
Hi, 
Thanks for releasing the code. I was trying to run the training script `train.py` but got the error `ModuleNotFoundError: No module named 'swag.utils'`. This is in the file `experiments/eigenvalues/train.py` line 13 - `import swag.utils as training_utils`. I could not find swag in your codebase or in the `setup.py`, and after installing a package swag, I got that error above.

**Comment by g-benton** [comment]
Hi,

Good question, the `swag` package you need can be found here: https://github.com/wjmaddox/swa_gaussian. I will be sure to update the package requirements accordingly.
